version: "3.8"
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: "sea-store-backend-items"
    depends_on:
      - postgre
    links:
      - postgre
    ports:
      - 9090:9090
    expose:
      - 9090

  postgre:
    image: postgres:9.6.19
    restart: always
    container_name: sea-store-backend-items-postgresql
    ports:
      - 9432:5432
    environment:
      - POSTGRES_PASSWORD=compfest2020!
      - POSTGRES_DB=items
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s

