version: "3.8"
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: komangyogananda/sea-store-backend-items:0.1
    container_name: "sea-store-backend-items"
    depends_on: 
      - postgre
    links: 
      - postgre
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: always
    volumes: 
      - .env:/app/.env
  postgre:
    image: postgres:9.6.19
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=compfest
      - POSTGRES_PASSWORD=compfest2020
      - POSTGRES_DB=items
    volumes: 
      - ~/dev/postgre:/var/lib/postgresql/data