version: "3.8"
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: komangyogananda/sea-store-backend-items:0.1
    container_name: "sea-store-backend-items"
    ports:
      - 9090:9090
    expose:
      - 9090
    command: bash -c "
      go run migrations/*.go init
      && go run migrations/*go
      && ./server"