// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/OLTeam-go/sea-store-backend-items/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteItem provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteItem(ctx context.Context, id string) (*models.Item, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fetch provides a mock function with given fields: ctx, page
func (_m *Repository) Fetch(ctx context.Context, page int) (*[]models.Item, error) {
	ret := _m.Called(ctx, page)

	var r0 *[]models.Item
	if rf, ok := ret.Get(0).(func(context.Context, int) *[]models.Item); ok {
		r0 = rf(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id string) (*models.Item, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMerchantID provides a mock function with given fields: cxt, merchantID, page
func (_m *Repository) GetByMerchantID(cxt context.Context, merchantID string, page int) (*[]models.Item, error) {
	ret := _m.Called(cxt, merchantID, page)

	var r0 *[]models.Item
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *[]models.Item); ok {
		r0 = rf(cxt, merchantID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(cxt, merchantID, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreItem provides a mock function with given fields: ctx, it
func (_m *Repository) StoreItem(ctx context.Context, it *models.Item) (*models.Item, error) {
	ret := _m.Called(ctx, it)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, *models.Item) *models.Item); ok {
		r0 = rf(ctx, it)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Item) error); ok {
		r1 = rf(ctx, it)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateItem provides a mock function with given fields: ctx, id, it
func (_m *Repository) UpdateItem(ctx context.Context, id string, it *models.Item) (*models.Item, error) {
	ret := _m.Called(ctx, id, it)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Item) *models.Item); ok {
		r0 = rf(ctx, id, it)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *models.Item) error); ok {
		r1 = rf(ctx, id, it)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
