basePath: /api
definitions:
  models.Item:
    properties:
      category:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      merchant_id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  rest.RequestIDs:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  rest.ResponseError:
    properties:
      message:
        type: string
    type: object
  rest.ResponsePagination:
    properties:
      data:
        type: object
      page:
        type: integer
      size:
        type: integer
      status:
        type: integer
    type: object
  rest.ResponseSuccess:
    properties:
      data:
        type: object
      status:
        type: integer
    type: object
host: sea-store-backend-items.herokuapp.com
info:
  contact:
    email: yoganandamahaputra@gmail.com
    name: OLTeamgo API Support
  description: Api Documentation for Service Items
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Service Items API
  version: "1.0"
paths:
  /item:
    post:
      consumes:
      - application/json
      description: Create new item based on json on
      parameters:
      - description: Created at, updated at, deleted at are optional and will be ignored
        in: body
        name: default
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/rest.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/models.Item'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to create new item
  /item/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an item based on the id
      parameters:
      - description: ID of an item
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/rest.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/models.Item'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to delete an item
    get:
      consumes:
      - application/json
      description: return item object
      parameters:
      - description: ID of an item
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/rest.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/models.Item'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to get an item by id
    patch:
      consumes:
      - application/json
      description: Update item based on provided data
      parameters:
      - description: Only Name, Category, Description, Quantity, and Price will be updated
        in: body
        name: default
        schema:
          $ref: '#/definitions/models.Item'
      - description: ID of an item
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/rest.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/models.Item'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to update an item
  /items:
    get:
      consumes:
      - application/json
      description: return array of item object
      parameters:
      - description: page index
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/rest.ResponsePagination'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Item'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to get items
    post:
      consumes:
      - application/json
      description: return array of item object
      parameters:
      - description: Request ID
        in: body
        name: default
        required: true
        schema:
          $ref: '#/definitions/rest.RequestIDs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to get items based on IDs
  /items/merchant/{merchant_id}:
    get:
      consumes:
      - application/json
      description: return array of item object
      parameters:
      - description: page index
        in: query
        name: page
        type: integer
      - description: merchant id
        in: path
        name: merchant_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/rest.ResponsePagination'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Item'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to get items based on the merchant ID
  /items/sold:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request ID
        in: body
        name: default
        required: true
        schema:
          $ref: '#/definitions/rest.RequestIDs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Endpoint to set items to be sold (quantitiy = 0)
swagger: "2.0"
