package rest

import (
	"net/http"

	dItems "github.com/OLTeam-go/sea-store-backend-items/delivery"
	_ "github.com/OLTeam-go/sea-store-backend-items/docs" // docs is generated by Swag CLI, you have to import it.
	uItems "github.com/OLTeam-go/sea-store-backend-items/usecase"
	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

type restDelivery struct {
	usecase uItems.Usecase
}

// New function initialize delivery used for the services
func New(e *echo.Echo, usecase uItems.Usecase) dItems.Delivery {
	handler := &restDelivery{
		usecase: usecase,
	}
	e.GET("/", func(c echo.Context) error {
		return c.JSON(http.StatusAccepted, "Hello from service items")
	})
	api := e.Group("/api")
	api.POST("/item", handler.StoreItem)
	api.DELETE("/item/:id", handler.DeleteItem)
	api.GET("/item/:id", handler.GetByID)
	api.PATCH("/item/:id", handler.UpdateItem)
	api.PUT("/item/:id", handler.UpdateItem)
	api.GET("/items/merchant/:merchant_id", handler.GetByMerchantID)
	api.GET("/items", handler.Fetch)
	api.POST("/items", handler.FetchByIDs)
	api.POST("/items/sold", handler.Sold)
	api.GET("/docs/*", echoSwagger.WrapHandler)
	return handler
}
